
package corsa;

/**
 * Pista è la finestra che contiene il percorso di gara
 * @author Andrea Vallorani
 */
public class Pista extends javax.swing.JFrame {
    
    int pos1;
    int pos2;
    int pos3;
    int pos4;
    int pos5;
    int pos6;
    int pos7;
    int pos8;
    int pos9;
    int pos10;
    
    public Pista() {
        initComponents();
        pos1= this.icoAtleta1.getX();
        pos2= this.icoAtleta2.getX();
        pos3= this.icoAtleta3.getX();
        pos4= this.icoAtleta4.getX();
        pos5= this.icoAtleta5.getX();
        pos6= this.icoAtleta6.getX();
        pos7= this.icoAtleta7.getX();
        pos8= this.icoAtleta8.getX();
        pos9= this.icoAtleta0.getX();
        pos10= this.icoAtleta10.getX();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        corsia1 = new javax.swing.JPanel();
        icoAtleta1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        bottoneAvvio = new javax.swing.JButton();
        statoGara = new javax.swing.JLabel();
        corsia4 = new javax.swing.JPanel();
        icoAtleta4 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        corsia5 = new javax.swing.JPanel();
        icoAtleta6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        corsia6 = new javax.swing.JPanel();
        icoAtleta5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        corsia7 = new javax.swing.JPanel();
        icoAtleta8 = new javax.swing.JLabel();
        corsia9 = new javax.swing.JPanel();
        icoAtleta9 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        corsia8 = new javax.swing.JPanel();
        icoAtleta0 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        corsia10 = new javax.swing.JPanel();
        icoAtleta10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        corsia11 = new javax.swing.JPanel();
        icoAtleta7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        corsia12 = new javax.swing.JPanel();
        icoAtleta3 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        corsia13 = new javax.swing.JPanel();
        icoAtleta2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        bottoneRiavvia1 = new javax.swing.JButton();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        posto1 = new java.awt.Label();
        posto3 = new java.awt.Label();
        posto2 = new java.awt.Label();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        corsia1.setBackground(new java.awt.Color(0, 102, 0));
        corsia1.setLayout(null);

        icoAtleta1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/corsa/bom.gif"))); // NOI18N
        corsia1.add(icoAtleta1);
        icoAtleta1.setBounds(0, 0, 80, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("1");
        jLabel1.setToolTipText("");
        corsia1.add(jLabel1);
        jLabel1.setBounds(330, 10, 8, 17);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        corsia1.add(jPanel1);
        jPanel1.setBounds(930, 0, 10, 40);

        bottoneAvvio.setText("VIA!");
        bottoneAvvio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottoneAvvioActionPerformed(evt);
            }
        });

        statoGara.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        statoGara.setText("Gara non ancora iniziata");

        corsia4.setBackground(new java.awt.Color(0, 102, 0));
        corsia4.setLayout(null);

        icoAtleta4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/corsa/bom.gif"))); // NOI18N
        corsia4.add(icoAtleta4);
        icoAtleta4.setBounds(0, 0, 80, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("4");
        corsia4.add(jLabel4);
        jLabel4.setBounds(330, 10, 8, 17);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        corsia4.add(jPanel4);
        jPanel4.setBounds(930, 0, 10, 40);

        corsia5.setBackground(new java.awt.Color(0, 102, 0));
        corsia5.setLayout(null);

        icoAtleta6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/corsa/bom.gif"))); // NOI18N
        corsia5.add(icoAtleta6);
        icoAtleta6.setBounds(0, 0, 80, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("6");
        corsia5.add(jLabel7);
        jLabel7.setBounds(330, 10, 8, 17);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        corsia5.add(jPanel6);
        jPanel6.setBounds(930, 0, 10, 40);

        corsia6.setBackground(new java.awt.Color(0, 102, 0));
        corsia6.setLayout(null);

        icoAtleta5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/corsa/bom.gif"))); // NOI18N
        corsia6.add(icoAtleta5);
        icoAtleta5.setBounds(0, 0, 80, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("5");
        corsia6.add(jLabel6);
        jLabel6.setBounds(330, 10, 8, 17);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        corsia6.add(jPanel5);
        jPanel5.setBounds(930, 0, 10, 40);

        corsia7.setBackground(new java.awt.Color(0, 102, 0));
        corsia7.setLayout(null);

        icoAtleta8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/corsa/bom.gif"))); // NOI18N
        corsia7.add(icoAtleta8);
        icoAtleta8.setBounds(0, 0, 80, 40);

        corsia9.setBackground(new java.awt.Color(255, 102, 0));
        corsia9.setLayout(null);

        icoAtleta9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/corsa/cavv.gif"))); // NOI18N
        corsia9.add(icoAtleta9);
        icoAtleta9.setBounds(0, 0, 80, 40);

        corsia7.add(corsia9);
        corsia9.setBounds(0, 0, 0, 0);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("8");
        corsia7.add(jLabel9);
        jLabel9.setBounds(330, 10, 8, 17);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        corsia7.add(jPanel8);
        jPanel8.setBounds(930, 0, 10, 40);

        corsia8.setBackground(new java.awt.Color(0, 102, 0));
        corsia8.setLayout(null);

        icoAtleta0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/corsa/bom.gif"))); // NOI18N
        corsia8.add(icoAtleta0);
        icoAtleta0.setBounds(0, 0, 80, 40);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("9");
        corsia8.add(jLabel10);
        jLabel10.setBounds(330, 10, 8, 17);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        corsia8.add(jPanel9);
        jPanel9.setBounds(930, 0, 10, 40);

        corsia10.setBackground(new java.awt.Color(0, 102, 0));
        corsia10.setLayout(null);

        icoAtleta10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/corsa/bom.gif"))); // NOI18N
        corsia10.add(icoAtleta10);
        icoAtleta10.setBounds(0, 0, 80, 40);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("10");
        corsia10.add(jLabel11);
        jLabel11.setBounds(330, 10, 16, 17);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        corsia10.add(jPanel10);
        jPanel10.setBounds(930, 0, 10, 40);

        corsia11.setBackground(new java.awt.Color(0, 102, 0));
        corsia11.setLayout(null);

        icoAtleta7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/corsa/bom.gif"))); // NOI18N
        corsia11.add(icoAtleta7);
        icoAtleta7.setBounds(0, 0, 80, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("7");
        corsia11.add(jLabel8);
        jLabel8.setBounds(330, 10, 8, 17);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        corsia11.add(jPanel7);
        jPanel7.setBounds(930, 0, 10, 40);

        corsia12.setBackground(new java.awt.Color(0, 102, 0));
        corsia12.setLayout(null);

        icoAtleta3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/corsa/bom.gif"))); // NOI18N
        corsia12.add(icoAtleta3);
        icoAtleta3.setBounds(0, 0, 80, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("3");
        corsia12.add(jLabel3);
        jLabel3.setBounds(330, 10, 8, 17);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        corsia12.add(jPanel3);
        jPanel3.setBounds(930, 0, 10, 40);

        corsia13.setBackground(new java.awt.Color(0, 102, 0));
        corsia13.setLayout(null);

        icoAtleta2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/corsa/bom.gif"))); // NOI18N
        corsia13.add(icoAtleta2);
        icoAtleta2.setBounds(0, 0, 80, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("2");
        corsia13.add(jLabel2);
        jLabel2.setBounds(330, 10, 8, 17);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        corsia13.add(jPanel2);
        jPanel2.setBounds(930, 0, 10, 40);

        bottoneRiavvia1.setText("RIAVVIA");
        bottoneRiavvia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottoneRiavvia1ActionPerformed(evt);
            }
        });

        label1.setText("1°");

        label2.setText("2°");

        label3.setText("3°");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bottoneAvvio, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bottoneRiavvia1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(statoGara)))
                        .addGap(603, 603, 603)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(posto2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(posto3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(posto1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(corsia10, javax.swing.GroupLayout.DEFAULT_SIZE, 994, Short.MAX_VALUE)
                        .addComponent(corsia8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(corsia7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(corsia11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(corsia5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(corsia6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(corsia4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(corsia12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(corsia13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(corsia1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(corsia1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(corsia13, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(corsia12, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(corsia4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(corsia6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(corsia5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(corsia11, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(corsia7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(corsia8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(corsia10, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(posto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(posto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                                .addComponent(posto3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(21, 35, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(statoGara)
                                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bottoneAvvio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bottoneRiavvia1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bottoneAvvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottoneAvvioActionPerformed
        Giudice giudice = new Giudice(this);
        giudice.start();
        this.bottoneAvvio.setEnabled(false);
        
    }//GEN-LAST:event_bottoneAvvioActionPerformed

    private void bottoneRiavvia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottoneRiavvia1ActionPerformed
        
        
        this.icoAtleta1.setLocation(pos1,this.icoAtleta1.getY());
        this.icoAtleta2.setLocation(pos2,this.icoAtleta2.getY());
        this.icoAtleta3.setLocation(pos3,this.icoAtleta3.getY());
        this.icoAtleta4.setLocation(pos4,this.icoAtleta4.getY());
        this.icoAtleta5.setLocation(pos5,this.icoAtleta5.getY());
        this.icoAtleta6.setLocation(pos6,this.icoAtleta6.getY());
        this.icoAtleta7.setLocation(pos7,this.icoAtleta7.getY());
        this.icoAtleta8.setLocation(pos8,this.icoAtleta8.getY());
        this.icoAtleta0.setLocation(pos9,this.icoAtleta0.getY());
        this.icoAtleta10.setLocation(pos10,this.icoAtleta10.getY());
        
        this.bottoneAvvio.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_bottoneRiavvia1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bottoneAvvio;
    private javax.swing.JButton bottoneRiavvia1;
    private javax.swing.JPanel corsia1;
    private javax.swing.JPanel corsia10;
    private javax.swing.JPanel corsia11;
    private javax.swing.JPanel corsia12;
    private javax.swing.JPanel corsia13;
    private javax.swing.JPanel corsia4;
    private javax.swing.JPanel corsia5;
    private javax.swing.JPanel corsia6;
    private javax.swing.JPanel corsia7;
    private javax.swing.JPanel corsia8;
    private javax.swing.JPanel corsia9;
    public javax.swing.JLabel icoAtleta0;
    public javax.swing.JLabel icoAtleta1;
    public javax.swing.JLabel icoAtleta10;
    public javax.swing.JLabel icoAtleta2;
    public javax.swing.JLabel icoAtleta3;
    public javax.swing.JLabel icoAtleta4;
    public javax.swing.JLabel icoAtleta5;
    public javax.swing.JLabel icoAtleta6;
    public javax.swing.JLabel icoAtleta7;
    public javax.swing.JLabel icoAtleta8;
    public javax.swing.JLabel icoAtleta9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    public java.awt.Label posto1;
    public java.awt.Label posto2;
    public java.awt.Label posto3;
    public javax.swing.JLabel statoGara;
    // End of variables declaration//GEN-END:variables
}
